import type { SidebarItem, PageMeta, DocConfig } from "../utils/types.js";
import { getMarkdownFiles, getSlugFromPath, readTextFile, exists } from "../utils/fs.js";
import { parseFrontmatter } from "../utils/frontmatter.js";
import { DEFAULT_ORDER } from "../core/constants/defaults.js";
import { join, basename } from "node:path";
import { getLocalePrefix } from "../utils/navigation.js";

export async function generateSidebar(
  docsDir: string,
  locale: string,
  configSidebar?: SidebarItem[],
  config?: DocConfig
): Promise<SidebarItem[]> {
  const localeDir = join(docsDir, locale);
  
  if (!(await exists(localeDir))) {
    return [];
  }
  
  const isDefaultLocale = config?.defaultLocale === locale;
  const prefix = config ? getLocalePrefix(locale, config) : locale;
  const files = await getMarkdownFiles(localeDir);
  const autoStructure = await buildStructure(files, localeDir, locale, prefix, isDefaultLocale);
  
  if (!configSidebar || configSidebar.length === 0) {
    return autoStructure;
  }
  
  const configItems = addLocalePrefix(configSidebar, locale, prefix, isDefaultLocale);
  const definedHrefs = new Set<string>();
  collectHrefs(configItems, definedHrefs);
  
  const autoItems = filterAutoItems(autoStructure, definedHrefs, locale);
  
  return mergeSidebars(configItems, autoItems);
}

function collectHrefs(items: SidebarItem[], hrefs: Set<string>): void {
  for (const item of items) {
    if (item.href) {
      hrefs.add(item.href);
    }
    if (item.items) {
      collectHrefs(item.items, hrefs);
    }
  }
}

function filterAutoItems(items: SidebarItem[], definedHrefs: Set<string>, locale: string): SidebarItem[] {
  const result: SidebarItem[] = [];
  
  for (const item of items) {
    if (item.href && definedHrefs.has(item.href)) {
      continue;
    }
    
    if (item.items) {
      const filteredItems = filterAutoItems(item.items, definedHrefs, locale);
      if (filteredItems.length > 0) {
        result.push({
          ...item,
          items: filteredItems,
        });
      }
    } else if (item.href) {
      result.push(item);
    }
  }
  
  return result;
}

function normalizeLabel(label: string): string {
  return label.toLowerCase().replace(/[-\s]/g, '');
}

function mergeSidebars(configItems: SidebarItem[], autoItems: SidebarItem[]): SidebarItem[] {
  const result: SidebarItem[] = [];
  
  for (const configItem of configItems) {
    if (configItem.items && configItem.items.length > 0) {
      const autoCategory = autoItems.find(
        a => a.items && normalizeLabel(a.label) === normalizeLabel(configItem.label)
      );
      
      if (autoCategory && autoCategory.items) {
        const configHrefs = new Set(configItem.items.map(i => i.href));
        const newAutoItems = autoCategory.items.filter(i => !configHrefs.has(i.href)).map(i => ({
          ...i,
          autoGenerated: true,
        }));
        
        result.push({
          ...configItem,
          items: [...configItem.items, ...newAutoItems],
        });
      } else {
        result.push(configItem);
      }
    } else {
      result.push(configItem);
    }
  }
  
  for (const autoItem of autoItems) {
    if (autoItem.items && autoItem.items.length > 0) {
      const existsInResult = result.some(
        r => r.items && normalizeLabel(r.label) === normalizeLabel(autoItem.label)
      );
      if (!existsInResult) {
        result.push({
          ...autoItem,
          autoGenerated: true,
          items: autoItem.items.map(i => ({ ...i, autoGenerated: true })),
        });
      }
    } else {
      const existsInResult = result.some(r => r.href === autoItem.href);
      if (!existsInResult) {
        result.push({ ...autoItem, autoGenerated: true });
      }
    }
  }
  
  return result;
}

function addLocalePrefix(items: SidebarItem[], locale: string, prefix: string, isDefaultLocale: boolean): SidebarItem[] {
  return items.map(item => ({
    ...item,
    href: item.href ? addLocaleToHref(item.href, locale, prefix, isDefaultLocale) : undefined,
    items: item.items ? addLocalePrefix(item.items, locale, prefix, isDefaultLocale) : undefined,
  }));
}

function addLocaleToHref(href: string, locale: string, prefix: string, isDefaultLocale: boolean): string {
  if (isDefaultLocale) {
    if (href.startsWith("/")) return href;
    return `/${href}`;
  }
  
  if (href.startsWith(`/${prefix}/`)) return href;
  if (href.startsWith(`/${locale}/`)) return href.replace(`/${locale}/`, `/${prefix}/`);
  if (href.startsWith("/")) return `/${prefix}${href}`;
  return `/${prefix}/${href}`;
}

interface FileEntry {
  slug: string;
  path: string;
  meta: PageMeta;
  isIndex: boolean;
}

async function buildStructure(files: string[], baseDir: string, _locale: string, prefix: string, isDefaultLocale: boolean): Promise<SidebarItem[]> {
  const entries: FileEntry[] = [];
  
  for (const file of files) {
    const slug = getSlugFromPath(baseDir, file);
    const content = await readTextFile(file);
    const { meta } = parseFrontmatter(content);
    
    if (meta.hide) continue;
    
    entries.push({
      slug,
      path: file,
      meta,
      isIndex: slug === "index" || slug.endsWith("/index"),
    });
  }
  
  entries.sort((a, b) => {
    const orderA = a.meta.order ?? DEFAULT_ORDER;
    const orderB = b.meta.order ?? DEFAULT_ORDER;
    if (orderA !== orderB) return orderA - orderB;
    return a.slug.localeCompare(b.slug);
  });
  
  const root: SidebarItem[] = [];
  const dirs: Map<string, SidebarItem> = new Map();
  
  for (const entry of entries) {
    const parts = entry.slug.split("/");
    const label = entry.meta.sidebar_label || entry.meta.title || basename(entry.slug);
    const baseHref = entry.isIndex
      ? `/${parts.slice(0, -1).join("/")}` || "/"
      : `/${entry.slug}`;
    const href = isDefaultLocale ? baseHref : `/${prefix}${baseHref}`;
    
    if (parts.length === 1 && !entry.isIndex) {
      root.push({ label, href });
    } else if (entry.isIndex) {
      const dirPath = parts.slice(0, -1).join("/");
      if (dirPath) {
        const dirItem: SidebarItem = {
          label,
          href: `/${prefix}/${dirPath}`,
          items: [],
        };
        dirs.set(dirPath, dirItem);
      }
    } else {
      const dirPath = parts[0];
      if (dirPath) {
        if (!dirs.has(dirPath)) {
          dirs.set(dirPath, {
            label: dirPath.charAt(0).toUpperCase() + dirPath.slice(1),
            items: [],
          });
        }
        const dirItem = dirs.get(dirPath);
        if (dirItem && dirItem.items) {
          dirItem.items.push({ label, href });
        }
      }
    }
  }
  
  for (const [, dirItem] of dirs) {
    root.push(dirItem);
  }
  
  return root;
}

export function flattenSidebar(items: SidebarItem[]): Array<{ label: string; href: string }> {
  const result: Array<{ label: string; href: string }> = [];
  
  for (const item of items) {
    if (item.href) {
      result.push({ label: item.label, href: item.href });
    }
    if (item.items) {
      result.push(...flattenSidebar(item.items));
    }
  }
  
  return result;
}
