export interface LocaleConfig {
  indexPage?: string;
  localePrefix?: string;
}

export interface DocConfig {
  readonly title: string;
  readonly description: string;
  readonly defaultLocale: string;
  locales: Record<string, LocaleConfig>;
  readonly base?: string;
  readonly sidebar?: SidebarConfig;
  readonly theme?: {
    readonly default: string;
  };
  readonly logo?: string | false;
}

export interface SidebarConfig {
  [locale: string]: SidebarItem[];
}

export interface SidebarItem {
  label: string;
  href?: string;
  items?: SidebarItem[];
  collapsed?: boolean;
  autoGenerated?: boolean;
}

export interface PageMeta {
  title: string;
  description?: string;
  order?: number;
  sidebar_label?: string;
  hide?: boolean;
}

export interface RouteParams {
  locale: string;
  path: string[];
  slug: string;
}

export interface SearchResult {
  title: string;
  href: string;
  excerpt: string;
  content: string;
  locale: string;
}

export interface Theme {
  name: string;
  label: string;
  vars: Record<string, string>;
}
