import type { SidebarItem, DocConfig } from "../../utils/types.js";
import { getLocalePrefix } from "../../utils/navigation.js";

export function renderSidebar(items: SidebarItem[], currentSlug: string, locale: string = "en", base: string = "", config?: DocConfig): string {
  const normalizeHref = (href: string): string => href.replace(/\/+$/, "");
  const prefix = config ? getLocalePrefix(locale, config) : locale;
  const isDefaultLocale = config?.defaultLocale === locale;
  
  const currentHref = isDefaultLocale 
    ? normalizeHref(`/${currentSlug}`)
    : normalizeHref(`/${prefix}/${currentSlug}`);
  const currentHrefNoLocale = normalizeHref(`/${currentSlug}`);
  
  return items
    .map((item) => {
      if (item.items && item.items.length > 0) {
        const hasActive = item.items.some(
          (sub) => sub.href && (normalizeHref(sub.href) === currentHref || normalizeHref(sub.href) === currentHrefNoLocale)
        );

        const categoryItems = item.items
          .map((sub) => {
            const isActive = sub.href && (normalizeHref(sub.href) === currentHref || normalizeHref(sub.href) === currentHrefNoLocale);
            const autoBadge = sub.autoGenerated ? ' <span class="auto-badge" title="Auto-generated">⚡</span>' : '';
            const href = sub.href ? base + sub.href : "#";
            return `<a href="${href}" class="sidebar-link preload ${isActive ? "active" : ""}">${sub.label}${autoBadge}</a>`;
          })
          .join("");

        const autoBadge = item.autoGenerated ? ' <span class="auto-badge" title="Auto-generated">⚡</span>' : '';
        return `
          <div class="sidebar-category ${hasActive ? "" : "collapsed"}">
            <div class="sidebar-category-header preload">
              <span>${item.label}${autoBadge}</span>
              <svg class="sidebar-category-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </div>
            <div class="sidebar-category-items">
              ${categoryItems}
            </div>
          </div>
        `;
      }

      const isActive = item.href && (normalizeHref(item.href) === currentHref || normalizeHref(item.href) === currentHrefNoLocale);
      const autoBadge = item.autoGenerated ? ' <span class="auto-badge" title="Auto-generated">⚡</span>' : '';
      const href = item.href ? base + item.href : "#";
      return `<a href="${href}" class="sidebar-link preload ${isActive ? "active" : ""}">${item.label}${autoBadge}</a>`;
    })
    .join("");
}
